#!/bin/sh

killall kanshi; kanshi &
# killall wm_pswall; wm_pswall &
killall sworkstyle; sworkstyle &
killall sway-alttab; sway-alttab &

killall aw-watcher-window-wayland; ~/.repo/aw-watcher-window-wayland/target/release/aw-watcher-window-wayland &
killall aw-watcher-spotify; ~/.repo/aw-watcher-spotify/aw-watcher-spotify &
