#!/bin/sh

# killall wm_pswall; wm_pswall &

pkill -f 'kanshi'; kanshi &
pkill -f 'sworkstyle'; sworkstyle &
pkill -f 'sway-alttab'; sway-alttab &
pkill -f 'aw-watcher-window-wayland'; aw-watcher-window-wayland &
pkill -f 'aw-watcher-spotify'; aw-watcher-spotify &
pkill -f 'aw-watcher-utilization'; aw-watcher-utilization &
