#!/bin/sh

# UTILS
# picom &
dunst &
# numlockx &
lxsession &
# ibus-daemon -drxR &
# unclutter &
# hushboard &
swayidle -w \
	timeout 1500 'swaylock' \
	timeout 1505 'swaymsg "output * dpms off"' \
	resume 'swaymsg "output * dpms on"' \
	before-sleep 'swaylock' &

brightnessctl s 5% &

# APPLICATION
# keeweb &
# remnote &
# blueman-applet &
# conky &
# optimus-manager-qt &
# LOCATION=$(curl -s "https://location.services.mozilla.com/v1/geolocate?key=geoclue" | awk 'OFS=":" {print $3,$5}' | tr -d ',}')
LOCATION=$(curl -s "https://location.services.mozilla.com/v1/geolocate?key=geoclue" | jq '.location | .lat,.lng' | paste -s -d ':')
gammastep -l $LOCATION &
thunderbird &
telegram-desktop -startintray &
slack -s -u &
discord --start-minimized &

# WEBAPP
# sleep 20
# messenger &
# calendar &

