#!/bin/sh

# daemons
# aw-qt &
dunst &
lxsession -n &
ibus-daemon -drxR &
foot --server &
# blueman-applet &
swayidle -w \
	timeout 3000 'swaylock -f' \
	timeout 3005 'swaymsg "output * dpms off"' resume 'swaymsg "output * dpms on"' \
	before-sleep 'playerctl pause' \
	before-sleep 'swaylock -f' \
	timeout 6000 '[ "$(cat /sys/class/power_supply/BAT1/status)" = "Discharging" ] && systemctl suspend' &



# graphical
footclient &
util_browse &
thunderbird &
# discord &
# keepassxc --keyfile "$PASS_KEYFILE" "$PASS_DATABASE" &

# brightnessctl s 0% &
# util_exmonctl -s 0% &

sleep 1
# clight &

# misc dependent daemons
sleep 5
gammastep
