#!/bin/sh

# UTILS
dunst &
lxsession &
fcitx5 &

swayidle -w \
	timeout 1500 'swaylock' \
	timeout 1505 'swaymsg "output * dpms off"' \
	resume 'swaymsg "output * dpms on"' \
	before-sleep 'swaylock' &

brightnessctl s 50% &

# APPLICATION
# LOCATION=$(curl -s "https://location.services.mozilla.com/v1/geolocate?key=geoclue" | awk 'OFS=":" {print $3,$5}' | tr -d ',}')
LOCATION=$(curl -s "https://location.services.mozilla.com/v1/geolocate?key=geoclue" | jq '.location | .lat,.lng' | paste -s -d ':')
gammastep -l $LOCATION &
thunderbird &
telegram-desktop -startintray &

# WEBRTC
systemctl --user stop pipewire pipewire-media-session xdg-desktop-portal xdg-desktop-portal-wlr
systemctl --user start pipewire-media-session
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway
