#! /bin/sh
bspc rule -r "*"

###---MONITORS---###
bspc monitor HDMI1 -d I II III IV V VI VII VIII IX X
bspc monitor eDP1 -d I II III IV V VI VII VIII IX X

###---AUTOSTART---###
lxsession &
xss-lock --transfer-sleep-lock -- slock &
ibus-daemon -drx &
redshift-gtk &
$HOME/.bin/extend.sh &
sxhkd &
hsetroot -solid "#990000" &
xrdb ~/.Xresources &

###---Monitor And Desktop Settings---###
bspc config bottom_padding	0
bspc config left_padding	0
bspc config right_padding	0
bspc config border_width	1
bspc config window_gap		5
bspc config active_border_color '#282828'
bspc config normal_border_color '#282828'
bspc config focused_border_color '#ebdbb2'

###---Global Settings---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config click_to_focus true

bspc config focus_follows_pointer 	    false
bspc config remove_disabled_monitors 	  true
bspc config remove_unplugged_monitors 	true
bspc config merge_overlapping_monitors 	true
