#!/bin/sh

# UTILS
picom &
dunst &
numlockx &
lxsession &
ibus-daemon -drxR &
unclutter &
hushboard &
xss-lock -- i3lock --color=000000 --show-failed-attempts &
brightnessctl s 5% &

# APPLICATION
# keeweb &
# remnote &
# blueman-applet &
# conky &
# optimus-manager-qt &
# LOCATION=$(curl -s "https://location.services.mozilla.com/v1/geolocate?key=geoclue" | awk 'OFS=":" {print $3,$5}' | tr -d ',}')
LOCATION=$(curl -s "https://location.services.mozilla.com/v1/geolocate?key=geoclue" | jq '.location | .lat,.lng' | paste -s -d ':')
gammastep -l $LOCATION &
mailspring --background &
telegram-desktop -startintray &
slack -s -u &
discord --start-minimized &

# WEBAPP
sleep 20
# messenger &
calendar &
