#!/bin/sh

#
picom &
dunst &

# utils
lxsession &
ibus-daemon -drxR &
unclutter &
hushboard &
# aw-qt &

# Application
# keeweb &
mailspring &
# remnote &
# udiskie &
blueman-applet &
# conky &
# optimus-manager-qt &

# Gammastep
LOCATION=$(curl -s "https://location.services.mozilla.com/v1/geolocate?key=geoclue" | awk 'OFS=":" {print $3,$5}' | tr -d ',}')
gammastep -l $LOCATION &

# Tray
telegram-desktop -startintray &
slack -s -u &
discord --start-minimized &

# Lock
xss-lock -- i3lock --color=000000 --show-failed-attempts &

# WEBAPP
sleep 20
messenger &
calendar &
