theme = "space-villain"
icons = "awesome"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "pomodoro"
length = 55
break_length = 5
message = "Take a break!"
break_message = "Back to work!"
use_nag = true
nag_path = "i3-nagbar"

[[block]]
block = "backlight"

[[block]]
block = "memory"
format_mem = "{mem_used}/{mem_total}({mem_used_percents})"
format_swap = "{swap_used}/{swap_total}({swap_used_percents})"
display_type = "memory"
icons = true
clickable = true
interval = 60
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "pacman"
interval = 7200
format = "{aur}"
format_up_to_date = "✓"
critical_updates_regex = "(linux|linux-lts|linux-zen)"
aur_command = "~/.config/i3status-rust/pacman_update"

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 60
format = "   {percentage} {time}"

[[block]]
block = "net"
device = "wlp3s0"
format = " {ssid} {signal_strength} {ip} "
interval = 60

[[block]]
block = "custom"
command = "echo '' $(uname -r)"
interval = "once"

[[block]]
block = "time"
interval = 60
timezone = "America/Mazatlan"
format = "US %R"

[[block]]
block = "time"
interval = 60
timezone = "Asia/Ho_Chi_Minh"
format = "VN %R"

[[block]]
block = "time"
interval = 60
format = "FI %R"


[[block]]
block = "time"
interval = 60
format = "%a %d/%m/%Y"
