theme = "space-villain"
icons = "awesome5"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "toggle"
command_state = "ibus engine | grep Bamboo"
command_on = "~/.bin/toggleibus"
command_off = "~/.bin/toggleibus"
interval = 60

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]
on_collapsed_click = "~/.bin/spotifyd"
on_click = "killall spotify"
marquee_interval = 60

[[block]]
block = "pomodoro"
length = 50
break_length = 10
message = "Take a break!"
break_message = "Back to work!"
notifier = "notifysend"

[[block]]
block = "backlight"

[[block]]
block = "memory"
format_mem = "{mem_used}/{mem_total}({mem_used_percents})"
format_swap = "{swap_used}/{swap_total}({swap_used_percents})"
display_type = "memory"
icons = true
clickable = true
interval = 60
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "pacman"
interval = 7200
format = "{aur}"
format_up_to_date = "✓"
critical_updates_regex = "(linux|linux-lts|linux-zen)"
aur_command = "~/.config/i3status-rust/pacman_update"

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 60
format = "   {percentage} {time}"

[[block]]
block = "bluetooth"
mac = "FC:58:FA:15:CB:7B"
format = "✓"
format_unavailable = "x"

[[block]]
block = "net"
device = "wlp3s0"
format = " {ssid} {signal_strength} {ip} "
interval = 60

[[block]]
block = "custom"
command = "echo '' $(uname -r)"
interval = "once"

[[block]]
block = "time"
interval = 60
timezone = "America/Mazatlan"
format = "US %R"

[[block]]
block = "time"
interval = 60
timezone = "Asia/Ho_Chi_Minh"
format = "VN %R"

[[block]]
block = "time"
interval = 60
format = "FI %R"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m/%Y"
