[icons]
name = "awesome5"

[theme]
name = "space-villain"

[theme.overrides]
idle_bg = "#101010"
idle_fg = "#ffffff"
info_bg = "#424242"
info_fg = "#ffffff"
good_bg = "#424242"
good_fg = "#ffffff"
warning_bg = "#424242"
warning_fg = "#ffffff"
critical_bg = "#ffffff"
critical_fg = "#424242"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"


# [[block]]
# block = "focused_window"
# max_width = 50
# show_marks = "visible"

# [[block]]
# block = "toggle"
# command_state = "ibus engine | grep Bamboo"
# command_on = "~/.sh/util_toggleibus"
# command_off = "~/.sh/util_toggleibus"
# interval = 60

[[block]]
block = "custom"
command = "i3-gnome-pomodoro status"
on_click = "i3-gnome-pomodoro toggle"
interval = 60

[[block]]
block = "music"
buttons = ["play", "next"]
marquee_interval = 60
on_click = "killall mpv; killall spotify"

# [[block]]
# block = "pomodoro"
# length = 50
# break_length = 10
# message = "Take a break!"
# break_message = "Back to work!"
# notifier = "notifysend"
# notifier_path = "~/.sh/wm_pomodoronoti"

[[block]]
block = "backlight"

[[block]]
block = "hueshift"
hue_shifter = "gammastep"
click_temp = 2000

[[block]]
block = "memory"
format_mem = "{mem_used}/{mem_total}({mem_used_percents})"
format_swap = "{swap_used}/{swap_total}({swap_used_percents})"
display_type = "memory"
icons = true
clickable = true
interval = 60
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "pacman"
interval = 7200
format = "{aur}"
format_up_to_date = "✓"
critical_updates_regex = "(linux|linux-lts|linux-zen)"
aur_command = "~/.sh/util_pendingupdate"

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 60
format = "   {percentage} {time}"

[[block]]
block = "bluetooth"
mac = "FC:58:FA:15:CB:7B"
format = "✓"
format_unavailable = "x"

[[block]]
block = "net"
device = "wlp3s0"
format = " {ssid} {signal_strength} {ip} "
interval = 60

# [[block]]
# block = "custom"
# command = "echo '' $(uname -r)"
# interval = "once"

[[block]]
block = "time"
interval = 60
timezone = "America/Mazatlan"
format = "US %R"

[[block]]
block = "time"
interval = 60
timezone = "Asia/Ho_Chi_Minh"
format = "VN %R"

[[block]]
block = "time"
interval = 60
format = "FI %R"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m/%Y"
