theme = "space-villain"
icons = "awesome"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "pomodoro"
length = 25
break_length = 5
message = "Take a break!"
break_message = "Back to work!"
use_nag = true
nag_path = "i3-nagbar"

[[block]]
block = "hueshift"
hue_shifter = "redshift"
step = 50
click_temp = 3000

[[block]]
block = "backlight"

[[block]]
block = "taskwarrior"
interval = 60
format = "{count} ({filter_name})"
format_singular = "{count} ({filter_name})"
format_everything_done = "✓"
warning_threshold = 3
critical_threshold = 5

[[block]]
block = "pacman"
interval = 600
format = "{aur}"
format_up_to_date = "✓"
critical_updates_regex = "(linux|linux-lts|linux-zen)"
aur_command = "~/.config/i3status-rust/pacman_update"

[[block]]
block = "sound"

[[block]]
block = "net"
device = "wlp3s0"
format = " {ssid} {signal_strength} {ip} "
interval = 60

[[block]]
block = "time"
interval = 60
timezone = "America/Mazatlan"
format = "US %R"

[[block]]
block = "time"
interval = 60
timezone = "Europe/Helsinki"
format = "FI %R"

[[block]]
block = "time"
interval = 60
format = "VN %R"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m/%Y"
